### ISSUE TITLE
I have 1 idea, can you see if it is?

### ISSUE THREAD

**Issue by KalvinThien** [SamuraiPolix/openbible-verse-scraper#5]
This project is great, however, I think it is necessary to download videos automatically from Pexels to have more diverse videos, no need to preload because it will weigh down unnecessary equipment.
2. Incorporating AI to create content would probably be better.
3. and I think if the video can be longer than 1 minute for TikTok Beta then it is a big step (merge more quotes to longer videos, add intro, outro ,...) 

How do you see this idea?

**Comment by SamuraiPolix** [comment]
You have some great ideas but I think you opened your issue in the wrong repository.
1. The reason I downloaded the videos from Pexels manually is because I didn't like all the videos and I wanted to pick them by hand.
2. I didn't use AI to create the content because I wanted to use bible verses and AI couldn't help with that. that was the goal of my project.
3. This can be done quite easily with some adjustments to the ffmpeg command but once again, it didn't fit the goal I had. :)

**Your ideas are absolutely amazing and I would love to see a project like this :)**
Feel free to fork the repository and add those things, I am here to help if you have any questions or if need anything!

**Comment by KalvinThien** [comment]
I have tried many other ways.
I use some Source API to get the Bible, then use Open AI analyze and return the right keyword and use that keyword to search and download Pexels.

I also refined to create more voice to read with Elevenlabs.
Your project is great !!
